@Library('pipeline-lib') _

pipeline {
    agent any

    parameters {
        booleanParam(
            name: 'Force',
            defaultValue: false,
            description: 'Runs all even if there are no changes'
        )
    }

    environment {
        PACKAGE            = 'frontend/package.json'
        PACKAGE_LOCK       = 'frontend/package-lock.json'
        JENKINS            = 'frontend/Jenkinsfile'
        CHANGE_SRC         = 'frontend/src/**'
        NGINX_CONF_PATH    = 'ci/nginx.conf'
        PROD_DOMAIN        = 'qrcool.ca'
        STATIC_SITE_DOMAIN = 'site.qrcool.ca'
    }

    stages {
        stage("Checkout") {
            steps {
                checkout scm
            }
        }

        stage("Install Dependencies") {
            when {
                anyOf {
                    changeset CHANGE_SRC
                    changeset JENKINS
                    changeset PACKAGE
                    changeset PACKAGE_LOCK
                    expression { return params.Force }
                }
            }
            steps {
                dir('frontend') {
                    sh 'NODE_ENV=development npm ci'

                    loadEnvFile('qrcool', 'frontend', 'staging')
                    loadEnvFile('qrcool', 'frontend', 'production')
                }
            }
        }

        stage("Vulnerability Check") {
            when {
                anyOf {
                    changeset CHANGE_SRC
                    changeset JENKINS
                    changeset PACKAGE
                    changeset PACKAGE_LOCK
                    expression { return params.Force }
                }
            }
            steps {
                dir('frontend') {
                    sh 'npm audit --audit-level=high'
                }
            }
        }

        stage("Build") {
            when {
                anyOf {
                    changeset CHANGE_SRC
                    changeset JENKINS
                    changeset PACKAGE
                    changeset PACKAGE_LOCK
                    expression { return params.Force }
                }
            }
            steps {
                dir('frontend') {
                    sh 'npm run build:prod'
                }
            }
        }

        stage("Deploy") {
            when {
                anyOf {
                    changeset CHANGE_SRC
                    changeset JENKINS
                    changeset PACKAGE
                    changeset PACKAGE_LOCK
                    expression { return params.Force }
                }
            }
            steps {
                script {
                    env.WWW_PATH = "/var/www/${STATIC_SITE_DOMAIN}/html"
                }
                dir('frontend') {
                    sh "mkdir -p ${env.WWW_PATH}"
                    sh "cp -r dist/* ${env.WWW_PATH}"
                }
            }
        }

        stage('Update Nginx') {
            environment {
                NGINX_BASE_PATH = '/opt/nginx'
            }
            when {
                anyOf {
                    changeset NGINX_CONF_PATH
                    changeset JENKINS
                    expression { return params.Force }
                }
            }
            steps {
                sh "cp ci/nginx.conf ${NGINX_BASE_PATH}/sites-available/${PROD_DOMAIN}"
                sh "ln -sfn ${NGINX_BASE_PATH}/sites-available/${PROD_DOMAIN} ${NGINX_BASE_PATH}/sites-enabled/${PROD_DOMAIN}"
                sh "docker exec nginx nginx -s reload"
            }
        }
    }
}
