services:
  qrcool:
    image: ghcr.io/orgclarkmiller/qrcool:${IMAGE_TAG:-latest}
    pull_policy: always
    container_name: qrcool
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "5000"
    networks:
      - web

networks:
  web:
    external: true
