export default [
    "You know you're my favourite right?",
    "As seen on tv",
    "Like and subscribe",
    "Hello world",
    "Is this thing on? 🎤",
    "Try out budgetbooze.ca",
    "Make sure to follow my linkedin clarkmiller.ca/linkedin",
    "I love you",
    "Stay tuned for more updates!",
    "Hope this made your day a little better.",
    "Keep going, you're doing great.",
    "Curiosity leads to the best discoveries.",
    "There's always more to learn.",
    "Appreciate you being here.",
    "Hope this added something good to your day.",
    "Keep at it!",
    "Big ideas start small.",
    "Drink some water, seriously.",
    "Progress is still progress.",
    "You've got this.",
    "More coming soon—stay tuned!",
    "Good vibes only.",
    "Take care out there.",
    "Keep moving forward.",
    "Focus on what matters.",
    "One step at a time.",
    "Find what inspires you.",
    "Creativity is a muscle—keep flexing it.",
    "Stay connected, stay engaged.",
    "Passion makes all the difference.",
    "Keep chasing what excites you.",
    "A little adventure never hurts.",
    "Push through the tough days.",
    "No limits, no excuses.",
    "Consistency wins every time.",
    "Confidence is built, not given.",
    "Believe in yourself, even when it's hard.",
    "Nothing stops you but you.",
    "Hope is underrated—hold onto it.",
    "Make your mark.",
    "Keep creating cool stuff!"
];